lib/contentfulex_web/router.ex
defmodule ContentfulexWeb.Router do
  use ContentfulexWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ContentfulexWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/recipes", RecipeController, only: [:index, :show]
  end

  # Other scopes may use custom stacks.
  # scope "/api", ContentfulexWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ContentfulexWeb.Telemetry
    end
  end
end

lib/contentfulex/application.ex
defmodule Contentfulex.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Contentfulex.Repo,
      # Start the Telemetry supervisor
      ContentfulexWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Contentfulex.PubSub},
      # Start the Endpoint (http/https)
      ContentfulexWeb.Endpoint
      # Start a worker by calling: Contentfulex.Worker.start_link(arg)
      # {Contentfulex.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Contentfulex.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ContentfulexWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/contentfulex/recipes.ex
defmodule Contentfulex.Recipes do
  @moduledoc """
  The Contentfulexs context.
  """

  import Contentful.Query
  alias Contentful.Delivery.Entries

  def list_recipes() do
    Entries
    |> content_type("recipe")
    |> fetch_all
    |> handle_entries()
  end

  def get_recipe!(id) do
    Entries |> fetch_one(id) |> handle_entry()
  end

  defp handle_entries({:ok, entries, total: _}) do
    Enum.map(entries, &parse/1)
  end

  defp handle_entries({:error, :not_found, _}), do: "Not found."

  defp handle_entry({:ok, entry}) do
    parse(entry)
  end

  defp handle_entry({:error, :not_found, _}), do: "Not found"

  defp parse(entry) do
    case entry do
      %{
        sys: %{id: id},
        fields: %{"description" => description, "title" => title}
      } ->
        %{id: id, description: description, title: title}

      _ ->
        %{}
    end
  end
end

lib/contentfulex/repo.ex
defmodule Contentfulex.Repo do
  use Ecto.Repo,
    otp_app: :contentfulex,
    adapter: Ecto.Adapters.Postgres
end

lib/contentfulex_web/controllers/page_controller.ex
defmodule ContentfulexWeb.PageController do
  use ContentfulexWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/contentfulex_web/controllers/recipe_controller.ex
defmodule ContentfulexWeb.RecipeController do
  use ContentfulexWeb, :controller

  alias Contentfulex.Recipes

  def index(conn, _params) do
    recipes = Recipes.list_recipes()
    render(conn, "index.html", recipes: recipes)
  end

  def show(conn, %{"id" => id}) do
    recipe = Recipes.get_recipe!(id)
    render(conn, "show.html", recipe: recipe)
  end
end

lib/contentfulex_web/views/error_view.ex
defmodule ContentfulexWeb.ErrorView do
  use ContentfulexWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/contentfulex_web/views/layout_view.ex
defmodule ContentfulexWeb.LayoutView do
  use ContentfulexWeb, :view
end

lib/contentfulex_web/views/page_view.ex
defmodule ContentfulexWeb.PageView do
  use ContentfulexWeb, :view
end

lib/contentfulex_web/views/recipe_view.ex
defmodule ContentfulexWeb.RecipeView do
  use ContentfulexWeb, :view
end

lib/contentfulex_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Contentfulex · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><%= link "Recipe", to: Routes.recipe_path(@conn, :index) %></li>
          </ul>
        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/contentfulex_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace of mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.5/CHANGELOG.md">v1.5 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
    </ul>
  </article>
</section>

lib/contentfulex_web/templates/recipe/index.html.eex
<h1>Listing Recipes</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for recipe <- @recipes do %>
    <tr>
      <td>
      </td>
      <td>
        <%= recipe.title %>
      </td>
      <td>
        <span><%= link "Show", to: Routes.recipe_path(@conn, :show, recipe.id) %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/contentfulex_web/templates/recipe/show.html.eex
<h1>Show Recipe</h1>

<ul>
  <li><strong>Title</strong> - <%= @recipe.title %></li>
  <li><strong>Description</strong> - <%= @recipe.description %></li>
</ul>

<span><%= link "Back", to: Routes.recipe_path(@conn, :index) %></span>